// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6pLC2uZKVjyTDeNP-MpenF8GV9YQ8dgI',
    appId: '1:205195699951:web:fb8f6d11ef8341ff549d1a',
    messagingSenderId: '205195699951',
    projectId: 'w3cst-57118',
    authDomain: 'w3cst-57118.firebaseapp.com',
    storageBucket: 'w3cst-57118.firebasestorage.app',
    measurementId: 'G-TFS03N96J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvSNnGDriO4DpoOwK0tjYPNk1-ABeeXJ8',
    appId: '1:205195699951:android:a2f0eca102fdddef549d1a',
    messagingSenderId: '205195699951',
    projectId: 'w3cst-57118',
    storageBucket: 'w3cst-57118.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRgUghvV-H4_-5o0j7LQY-bleqWIMnBP4',
    appId: '1:205195699951:ios:4e18e7883fccf7ea549d1a',
    messagingSenderId: '205195699951',
    projectId: 'w3cst-57118',
    storageBucket: 'w3cst-57118.firebasestorage.app',
    iosBundleId: 'com.example.w3cst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRgUghvV-H4_-5o0j7LQY-bleqWIMnBP4',
    appId: '1:205195699951:ios:4e18e7883fccf7ea549d1a',
    messagingSenderId: '205195699951',
    projectId: 'w3cst-57118',
    storageBucket: 'w3cst-57118.firebasestorage.app',
    iosBundleId: 'com.example.w3cst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6pLC2uZKVjyTDeNP-MpenF8GV9YQ8dgI',
    appId: '1:205195699951:web:abdbe9b1b3e78174549d1a',
    messagingSenderId: '205195699951',
    projectId: 'w3cst-57118',
    authDomain: 'w3cst-57118.firebaseapp.com',
    storageBucket: 'w3cst-57118.firebasestorage.app',
    measurementId: 'G-305D03QYTS',
  );
}
